### ISSUE TITLE
Intent does not change exiting an input

### ISSUE THREAD

**Issue by Kal-Aster** [ten1seven/what-input#114]
Hi, this module is great!
I haven't try it yet, but I was looking to the [demo](https://ten1seven.github.io/what-input/).

I noticed that the following steps did not trigger the "keyboard" intent:
- selecting with "mouse" or "touch" the "Example Text Input" input
- writing something
- pressing tab to focus the "Selection" select

Here I expect the intent to change to "keyboard", beacause I am using it to switch focused element, but it stays at "mouse".

**Comment by ten1seven** [comment]
Hi @Kal-Aster!

What you're seeing is expected behavior. Check out the section in the README on [interacting with forms](https://github.com/ten1seven/what-input#interacting-with-forms). Essentially, since even mouse users use the keyboard when using a form, the `what-intent` feature smooths that out by "remembering" that the mouse was being used up until the form interaction and preserves the mouse indication that you're seeing. The `what-input` feature switches immediately, so you can use whichever flavor of input switching is right for your use.

**Comment by Kal-Aster** [comment]
Thank you for the quick response!
