### ISSUE TITLE
Keyboard becomes mouse when there is long links

### ISSUE THREAD

**Issue by stevenbriscoeca** [ten1seven/what-input#32]
![what-input](https://cloud.githubusercontent.com/assets/3018441/14820280/fc53ec8c-0b93-11e6-8a3c-4bd2c4c25b37.gif)

http://codepen.io/stephendesjardins/pen/MyqQLd

The bug is when I tab into a button with a long link, Chrome renders the long link after a few seconds and causes data-what-input to become a mouse. I tried disconnecting my mouse and the data still changes to mouse.

Windows Chrome  50.0.2657.0 (64-bit)

**Comment by ten1seven** [comment]
That is indeed curious. However since it's specific to Chrome on Windows (doesn't happen in Chrome OS X) and is triggered by their browser chrome I'm of the opinion that it's a Chrome bug and not something I can address in What Input. I submitted a bug report to Chrome using [this CodePen](http://codepen.io/ten1seven/pen/xVaWMX) that isolates the events to show that it's not specific to What Input.

Thanks for bringing it up!
