### ISSUE TITLE
Interacting with button elements

### ISSUE THREAD

**Issue by alexvb** [ten1seven/what-input#43]
What Input currently doesn't update the input method when `<button>` elements are being interacted with. Since buttons are not only used to interact with a form, would you consider removing it from the list of 'blacklisted' elements?

**Comment by ten1seven** [comment]
This is correct and desired behavior and actually why what input was first created. Since buttons can be used within forms _and_ for triggering behavior outside of forms, it was visually confusing when they were clicked by mouse users and they held and visually displayed focus. The old solution was to remove the focus indicator, but that disadvantaged keyboard users. What input solves the issue of allowing a developer to suppress a focus indicator for mouse users but display it for keyboard users.

**Comment by ten1seven** [comment]
(disregard my last comment if it came through)

**Comment by ten1seven** [comment]
Yes, this seems reasonable. Give me a day to check it out and get back to you with a new release.
