### ISSUE TITLE
whatinput interfering with HTML calendar widget?

### ISSUE THREAD

**Issue by studio96** [ten1seven/what-input#89]
Hi,

Using Adobe Muse I publish a holiday booking site using html widgets from booklet.co.uk for calendars and availability. 

Recently the calendar on the mobile site has not been performing - the date picker sometimes holds and does not select the date, or it selects after a lag. This is on an iPhone (i have a 6s, not sure what the client has, but it is an iPhone)

Bookalet think that either whatinput or touchswipe might be interfering with the calendar. I can't unpick the code from Adobe Muse so am not able to specifically eliminate either but wondered if there was a view on this or something else I can try to test / eliminate? 

https://www.kingsdownholidayhomes.co.uk/kingsdown-park.html  will redirect to the mobile site with the availability calendar or https://www.kingsdownholidayhomes.co.uk/phone/kingsdown-park.html directly

Will also post on the touchswipe page and have opened a thread on Adobe Muse forums. 

Thanks in advance

**Comment by ten1seven** [comment]
Hi @studio96,

I'm sorry you're having trouble with your site. I did an unscientific test of visiting the phone-specific link that you sent and then https://www.carolsplaces.com/, another site that uses the bookalet widget but doesn't use What Input or TuochSwipe. I could tell that the calendar widget on carolsplaces.com did seem to be snappier to react to touch inputs.

What Input is written to be a pretty passive utility in that it only binds event listeners to the `<body>` and waits for events to bubble up. There's no blocking, "buffering", or any other interference of events. I would generally suspect that What Input isn't to blame. Unfortunately, it's impossible to debug someone else's site where some scripts can't be removed to isolate the problem.

TouchSwipe, _does_ use event buffering to wait before dispatching an event to determine what kind of touch event is happening. This could be where the interaction lag is happening, as even a small delay can make an app feel sluggish or broken. Here are the lines where the time thresholds are set: https://github.com/mattbryson/TouchSwipe-Jquery-Plugin/blob/master/jquery.touchSwipe.js#L215-L218 TouchSwipe hasn't been developed since 2015 and your site is running version 1.6.6 (put out in 2014). It looks like there have been some bug fixes since then, like https://github.com/mattbryson/TouchSwipe-Jquery-Plugin/blob/master/jquery.touchSwipe.js#L113 that might have improved on some of the issues you're experiencing.

I would suggest that you reach out to Adobe about having TouchSwipe and What Input updated to the most current versions. That might be a long process, but is likely your best route if you want to keep your site on Adobe Muse.

**Comment by studio96** [comment]
Hi @ten1seven and many thanks for your reply over the festive period. I really appreciate your investigations. I looked at carolsplaces and found the calendar to be laggy or unresponsive too, so it's an interesting comparison which I will go back to booklet with. 

I will raise this with Adobe too, the you are probably aware that Muse is EOL and this is unlikely to updated, so I am already looking to transition to another platform (most likely Blocs for existing clients or Wix on a pay per site basis). 

I'll report back with anything further, 

Kind regards, 

Andrew

**Comment by studio96** [comment]
Hi again, 

Could you confirm which device you tested the sites on, please? Here, the issue seems to appear on iOS for Kingsdown and http://strawberryfieldpark.co.uk but not on Android. Bookalet have also asked us to test isleofmullcottages.com which actually seems fine on iOS for me. Could I trouble you to identify the device you used, please?

Thanks

**Comment by ten1seven** [comment]
I used my personal device: iPhone 8 running iOS 12.1.2. I also used the Xcode device simulator and tested an iPhone 6 running iOS 12.1.

I tried out isleofmullcottages.com and the interactions times seemed pretty quick.

**Comment by studio96** [comment]
Hi, thanks for the response.

Bookalet have reverted to usinbg the iOS or Android native date picker which has resolved the issue - appreciate your assistance. 

Thanks 

Studio96
